### ISSUE TITLE
Error when running example code from node. "Type Error: xmlhttpImplClass is not a constructor"

### ISSUE THREAD

**Issue by Remixt** [clover/remote-pay-cloud#119]
```
TypeError: xmlHttpImplClass is not a constructor
    at new HttpSupport (C:\Users\Clay\Desktop\Clover 2.0\node_modules\remote-pay-cloud\dist\com\clover\util\HttpSupport.js:14:24)
    at new LegacyCloverConnector (C:\Users\Clay\Desktop\Clover 2.0\node_modules\remote-pay-cloud\dist\com\clover\remote\client\CloverConnectorFactory.js:51:29)
    at CloverConnectorFactory.createICloverConnector (C:\Users\Clay\Desktop\Clover 2.0\node_modules\remote-pay-cloud\dist\com\clover\remote\client\CloverConnectorFactory.js:29:16)
    at Object.<anonymous> (C:\Users\Clay\Desktop\Clover 2.0\index.js:7:53)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Function.Module.runMain (module.js:665:10)
```

Got this error when attempted to run unaltered example javascript.

**Comment by david-clover-com** [comment]
@Remixt, the SDK requires a websocket and XMLHttpRequest implementation.  These are provided by the browser in a web application, but must be provided when running outside of the browser.  In a Node environment we recommend the following libraries:

- websocket -  https://www.npmjs.com/package/ws
- XMLHttpRequest - https://www.npmjs.com/package/xmlhttprequest-ssl

An example of creating your WebSocketCloudCloverDeviceConfiguration with the recommended libraries:

```
const XMLHttpRequest = require("xmlhttprequest-ssl").XMLHttpRequest;
const WebSocket = require('ws');
...
deviceConfiguration = new clover.WebSocketCloudCloverDeviceConfiguration(
                "yourAppId",
                new WebSocket(yourEndPoint, options),
                new clover.ImageUtil(),
                "cloverServer",
                "accessToken",
                new clover.HttpSupport(XMLHttpRequest),
                "yourMerchantId",
                "yourDeviceUUID",
                "friendlyId",
                false);
```
We recently completed a working example for Node which has not been published yet.  I am hopeful that this will be published soon as it will provide you with a complete working example.

**Comment by Remixt** [comment]
What about the parameters for network device configuration instead of connecting through the clover cloud? WebSocketPairedCloverDeviceConfiguration.call

**Comment by david-clover-com** [comment]
Assuming you have access to Network Pay Display (in beta, not yet published) ...

WebSocketPairedCloverDeviceConfiguration requires the websocket library but does not require the XmlHttpRequest library.  

```
new clover.WebSocketPairedCloverDeviceConfiguration(
        endpoint,
        applicationId,
        posName,
        serialNumber,
        authToken,
        new WebSocket(yourEndPoint, options),
        new clover.ImageUtil());
```

**Comment by Remixt** [comment]
Thanks for the quick reply. I have those parameters, but nothing happens when running the program from node. I have access to network pay display on my clover mini device, and I've connected to it using a browser just fine. The source code I used is almost purely from the documentation, but here is what I have.

```
const clover = require('remote-pay-cloud');
const XMLHttpRequest = require('xmlhttprequest');
const WebSocket = require('ws');

var ExampleWebsocketPairedCloverDeviceConfiguration = function() {
   clover.WebSocketPairedCloverDeviceConfiguration.call(this,
       "ws://192.168.1.65:5678/remote_pay", // endpoint
       "com.cloverconnector.javascript.simple.sample:1.4", // Application Id
       "Javascript Simple Sample", // posName

       "Register_1", // serialNumber

       null, // authToken

       new WebSocket("ws://192.168.1.65:5678/remote_pay"), // webSocketFactory

       new clover.ImageUtil());
};

ExampleWebsocketPairedCloverDeviceConfiguration.prototype = Object.create(clover.WebSocketPairedCloverDeviceConfiguration.prototype);
ExampleWebsocketPairedCloverDeviceConfiguration.prototype.constructor = ExampleWebsocketPairedCloverDeviceConfiguration;

ExampleWebsocketPairedCloverDeviceConfiguration.prototype.onPairingCode = function(pairingCode) {
   console.log("Pairing code is " + pairingCode);
};

ExampleWebsocketPairedCloverDeviceConfiguration.prototype.onPairingSuccess = function(authToken) {
   console.log("Pairing succeeded, authToken is " + authToken);
};
var networkConfiguration = new ExampleWebsocketPairedCloverDeviceConfiguration();

var builderConfiguration = {};
builderConfiguration[clover.CloverConnectorFactoryBuilder.FACTORY_VERSION] = clover.CloverConnectorFactoryBuilder.VERSION_12;
var cloverConnectorFactory = clover.CloverConnectorFactoryBuilder.createICloverConnectorFactory(builderConfiguration);

var cloverConnector = cloverConnectorFactory.createICloverConnector(networkConfiguration);

var ExampleCloverConnectorListener = function (cloverConnector, progressinfoCallback) {
   clover.remotepay.ICloverConnectorListener.call(this);
   this.cloverConnector = cloverConnector;
   this.progressinfoCallback = progressinfoCallback;
   this.testStarted = false;
};
ExampleCloverConnectorListener.prototype = Object.create(clover.remotepay.ICloverConnectorListener.prototype);
ExampleCloverConnectorListener.prototype.constructor = ExampleCloverConnectorListener;

ExampleCloverConnectorListener.prototype.onDeviceReady = function (merchantInfo) {
    console.log("It's working");

};

ExampleCloverConnectorListener.prototype.onDeviceDisconnected = function(request) {

};

ExampleCloverConnectorListener.prototype.onDeviceConnected = function (request) {
    console.log("It's working");

};
var connectorListener = new ExampleCloverConnectorListener(cloverConnector);
cloverConnector.addCloverConnectorListener(connectorListener);
cloverConnector.initializeConnection();
```

**Comment by david-clover-com** [comment]
Is NPD running secure (wss) or non-secure (ws)?

**Comment by Remixt** [comment]
I changed it to non-secure for troubleshooting.
[screenshot](https://imgur.com/a/VQ9bm)

**Comment by david-clover-com** [comment]
My bad, replace the websocket section with a function  that returns a new websocket.

**Comment by Remixt** [comment]
Still getting the same results, is this what you intended or did I misunderstand?
```
var wsfunction = function() {
    return new WebSocket("ws://192.168.1.65:5678/remote_pay");
}

var ExampleWebsocketPairedCloverDeviceConfiguration = function() {
   clover.WebSocketPairedCloverDeviceConfiguration.call(this,
       "ws://192.168.1.65:5678/remote_pay", // endpoint
       "com.cloverconnector.javascript.simple.sample:1.4", // Application Id
       "Javascript Simple Sample", // posName

       "Register_1", // serialNumber

       null, // authToken

       wsfunction(), // webSocketFactory

       new clover.ImageUtil());
};
```

**Comment by david-clover-com** [comment]
Close, don't execute your function.

**Comment by Remixt** [comment]
Hmm, still isn't working.

**Comment by Remixt** [comment]
@david-clover-com I've tried both the cloud and direct network pay connections, but nothing seems to be happening. **Since I'm defining a different web socket factory than the default one for browsers, is there anything that would also need to be changed as far as listeners go?** Thanks for the help by the way, I really appreciate it.

**Comment by david-clover-com** [comment]
Sorry, it has been awhile since I looked at the Node code and I didn't give you the correct information.  The factory function needs to return a CloverWebSocketInterface which is an abstraction we designed for this purpose (not running in a browser).  I just tested your example and here is the working code (changed code only):

```
const endpoint = "ws://yourip:yourport/remote_pay";

var webSocketFactory = function () {
    let webSocketOverrides = {
        createWebSocket: function () {
            // To support self-signed certificates you must pass rejectUnauthorized = false.
            // https://github.com/websockets/ws/blob/master/examples/ssl.js
            let sslOptions = {
                rejectUnauthorized: false
            };
            // Use the ws library by default.
            return new WebSocket(endpoint, sslOptions);
        }
    }
    return Object.assign(new clover.CloverWebSocketInterface(endpoint), webSocketOverrides);
};

var ExampleWebsocketPairedCloverDeviceConfiguration = function () {
    clover.WebSocketPairedCloverDeviceConfiguration.call(this,
        endpoint, // endpoint
        "com.cloverconnector.javascript.simple.sample:1.4", // Application Id
        "Javascript Simple Sample", // posName
        "Register_1", // serialNumber
        null, // authToken().get(
        webSocketFactory,
        new clover.ImageUtil());
};
```

**Comment by Remixt** [comment]
It works! Thanks very much.
